#!/bin/sh

latest_image=$(docker images --format "{{.ID}} {{.CreatedAt}}" | sort -rk 2 | awk 'NR==1{print $1}')

export TEST_TARGET_IMAGE=${1:-$latest_image}
export DIR=`dirname $0`

# Assumes this script is in the func-tests base dir
cd $DIR

if [[ -z $JIRA_TEST_LICENSE ]]; then
    echo "You need to define JIRA_TEST_LICENSE env variable"
    exit 1
fi

sh ./postgres/inject-license

echo "######## Docker details ########"
docker version

echo "######## docker-compose details ########"
docker-compose version

echo "######## Python details ########"
python --version

echo "######## Running docker-compose now... ########"
docker-compose --verbose rm -f && \
    docker-compose up --force-recreate --always-recreate-deps --abort-on-container-exit --exit-code-from smoketests
